spring.datasource.url=${PLATEMATE_DB_URL}
spring.datasource.username=${PLATEMATE_DB_USERNAME}
spring.datasource.password=${PLATEMATE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
vaadin.productionMode=true
