spring.datasource.url=${PLATEMATE_DB_URL:jdbc:postgresql://localhost:5432/platemate}
spring.datasource.username=${PLATEMATE_DB_USERNAME:platemate}
spring.datasource.password=${PLATEMATE_DB_PASSWORD:platemate}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
